// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: pkg/proto/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	player_info "mafia/pkg/proto/player_info"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_CONNECTION_NEW_PLAYER NotificationType = 0
	NotificationType_START_GAME            NotificationType = 2
	NotificationType_WAKE                  NotificationType = 3
	NotificationType_VOTING                NotificationType = 4
	NotificationType_VOTING_RESULT         NotificationType = 5
	NotificationType_ROLE_PUBLICATION      NotificationType = 6
	NotificationType_RECEIVE_MESSAGE       NotificationType = 7
	NotificationType_FINISH                NotificationType = 8
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "CONNECTION_NEW_PLAYER",
		2: "START_GAME",
		3: "WAKE",
		4: "VOTING",
		5: "VOTING_RESULT",
		6: "ROLE_PUBLICATION",
		7: "RECEIVE_MESSAGE",
		8: "FINISH",
	}
	NotificationType_value = map[string]int32{
		"CONNECTION_NEW_PLAYER": 0,
		"START_GAME":            2,
		"WAKE":                  3,
		"VOTING":                4,
		"VOTING_RESULT":         5,
		"ROLE_PUBLICATION":      6,
		"RECEIVE_MESSAGE":       7,
		"FINISH":                8,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_pkg_proto_notification_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

type ConnectionNewPlayerNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *ConnectionNewPlayerNotification) Reset() {
	*x = ConnectionNewPlayerNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionNewPlayerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionNewPlayerNotification) ProtoMessage() {}

func (x *ConnectionNewPlayerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionNewPlayerNotification.ProtoReflect.Descriptor instead.
func (*ConnectionNewPlayerNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionNewPlayerNotification) GetPlayer() *player_info.PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type StartGameNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *StartGameNotification) Reset() {
	*x = StartGameNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameNotification) ProtoMessage() {}

func (x *StartGameNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameNotification.ProtoReflect.Descriptor instead.
func (*StartGameNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameNotification) GetPlayer() *player_info.PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type WakeNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remaining    []*player_info.PlayerInfo `protobuf:"bytes,1,rep,name=remaining,proto3" json:"remaining,omitempty"`
	KilledPlayer *player_info.PlayerInfo   `protobuf:"bytes,2,opt,name=killed_player,json=killedPlayer,proto3,oneof" json:"killed_player,omitempty"`
}

func (x *WakeNotification) Reset() {
	*x = WakeNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WakeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeNotification) ProtoMessage() {}

func (x *WakeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeNotification.ProtoReflect.Descriptor instead.
func (*WakeNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *WakeNotification) GetRemaining() []*player_info.PlayerInfo {
	if x != nil {
		return x.Remaining
	}
	return nil
}

func (x *WakeNotification) GetKilledPlayer() *player_info.PlayerInfo {
	if x != nil {
		return x.KilledPlayer
	}
	return nil
}

type VotingNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voter     *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate *player_info.PlayerInfo `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *VotingNotification) Reset() {
	*x = VotingNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VotingNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotingNotification) ProtoMessage() {}

func (x *VotingNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotingNotification.ProtoReflect.Descriptor instead.
func (*VotingNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *VotingNotification) GetVoter() *player_info.PlayerInfo {
	if x != nil {
		return x.Voter
	}
	return nil
}

func (x *VotingNotification) GetCandidate() *player_info.PlayerInfo {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type VotingResultNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutedPlayer *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=executed_player,json=executedPlayer,proto3,oneof" json:"executed_player,omitempty"`
}

func (x *VotingResultNotification) Reset() {
	*x = VotingResultNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VotingResultNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotingResultNotification) ProtoMessage() {}

func (x *VotingResultNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotingResultNotification.ProtoReflect.Descriptor instead.
func (*VotingResultNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *VotingResultNotification) GetExecutedPlayer() *player_info.PlayerInfo {
	if x != nil {
		return x.ExecutedPlayer
	}
	return nil
}

type RolePublicationNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *RolePublicationNotification) Reset() {
	*x = RolePublicationNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePublicationNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePublicationNotification) ProtoMessage() {}

func (x *RolePublicationNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePublicationNotification.ProtoReflect.Descriptor instead.
func (*RolePublicationNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *RolePublicationNotification) GetPlayer() *player_info.PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type ReceiveMessageNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  *player_info.PlayerInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReceiveMessageNotification) Reset() {
	*x = ReceiveMessageNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveMessageNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessageNotification) ProtoMessage() {}

func (x *ReceiveMessageNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessageNotification.ProtoReflect.Descriptor instead.
func (*ReceiveMessageNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveMessageNotification) GetSender() *player_info.PlayerInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ReceiveMessageNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FinishNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasMafiaWon bool `protobuf:"varint,1,opt,name=has_mafia_won,json=hasMafiaWon,proto3" json:"has_mafia_won,omitempty"`
}

func (x *FinishNotification) Reset() {
	*x = FinishNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishNotification) ProtoMessage() {}

func (x *FinishNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishNotification.ProtoReflect.Descriptor instead.
func (*FinishNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *FinishNotification) GetHasMafiaWon() bool {
	if x != nil {
		return x.HasMafiaWon
	}
	return false
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Notifications:
	//
	//	*Notification_ConnectionNewPlayerNotification
	//	*Notification_StartGameNotification
	//	*Notification_WakeNotification
	//	*Notification_VotingNotification
	//	*Notification_VotingResultNotification
	//	*Notification_RolePublicationNotification
	//	*Notification_ReceiveMessageNotification
	//	*Notification_FinishNotification
	Notifications isNotification_Notifications `protobuf_oneof:"notifications"`
	Type          NotificationType             `protobuf:"varint,10,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_notification_notification_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (m *Notification) GetNotifications() isNotification_Notifications {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (x *Notification) GetConnectionNewPlayerNotification() *ConnectionNewPlayerNotification {
	if x, ok := x.GetNotifications().(*Notification_ConnectionNewPlayerNotification); ok {
		return x.ConnectionNewPlayerNotification
	}
	return nil
}

func (x *Notification) GetStartGameNotification() *StartGameNotification {
	if x, ok := x.GetNotifications().(*Notification_StartGameNotification); ok {
		return x.StartGameNotification
	}
	return nil
}

func (x *Notification) GetWakeNotification() *WakeNotification {
	if x, ok := x.GetNotifications().(*Notification_WakeNotification); ok {
		return x.WakeNotification
	}
	return nil
}

func (x *Notification) GetVotingNotification() *VotingNotification {
	if x, ok := x.GetNotifications().(*Notification_VotingNotification); ok {
		return x.VotingNotification
	}
	return nil
}

func (x *Notification) GetVotingResultNotification() *VotingResultNotification {
	if x, ok := x.GetNotifications().(*Notification_VotingResultNotification); ok {
		return x.VotingResultNotification
	}
	return nil
}

func (x *Notification) GetRolePublicationNotification() *RolePublicationNotification {
	if x, ok := x.GetNotifications().(*Notification_RolePublicationNotification); ok {
		return x.RolePublicationNotification
	}
	return nil
}

func (x *Notification) GetReceiveMessageNotification() *ReceiveMessageNotification {
	if x, ok := x.GetNotifications().(*Notification_ReceiveMessageNotification); ok {
		return x.ReceiveMessageNotification
	}
	return nil
}

func (x *Notification) GetFinishNotification() *FinishNotification {
	if x, ok := x.GetNotifications().(*Notification_FinishNotification); ok {
		return x.FinishNotification
	}
	return nil
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_CONNECTION_NEW_PLAYER
}

type isNotification_Notifications interface {
	isNotification_Notifications()
}

type Notification_ConnectionNewPlayerNotification struct {
	ConnectionNewPlayerNotification *ConnectionNewPlayerNotification `protobuf:"bytes,1,opt,name=connection_new_player_notification,json=connectionNewPlayerNotification,proto3,oneof"`
}

type Notification_StartGameNotification struct {
	StartGameNotification *StartGameNotification `protobuf:"bytes,3,opt,name=start_game_notification,json=startGameNotification,proto3,oneof"`
}

type Notification_WakeNotification struct {
	WakeNotification *WakeNotification `protobuf:"bytes,4,opt,name=wake_notification,json=wakeNotification,proto3,oneof"`
}

type Notification_VotingNotification struct {
	VotingNotification *VotingNotification `protobuf:"bytes,5,opt,name=voting_notification,json=votingNotification,proto3,oneof"`
}

type Notification_VotingResultNotification struct {
	VotingResultNotification *VotingResultNotification `protobuf:"bytes,6,opt,name=voting_result_notification,json=votingResultNotification,proto3,oneof"`
}

type Notification_RolePublicationNotification struct {
	RolePublicationNotification *RolePublicationNotification `protobuf:"bytes,7,opt,name=role_publication_notification,json=rolePublicationNotification,proto3,oneof"`
}

type Notification_ReceiveMessageNotification struct {
	ReceiveMessageNotification *ReceiveMessageNotification `protobuf:"bytes,8,opt,name=receive_message_notification,json=receiveMessageNotification,proto3,oneof"`
}

type Notification_FinishNotification struct {
	FinishNotification *FinishNotification `protobuf:"bytes,9,opt,name=finish_notification,json=finishNotification,proto3,oneof"`
}

func (*Notification_ConnectionNewPlayerNotification) isNotification_Notifications() {}

func (*Notification_StartGameNotification) isNotification_Notifications() {}

func (*Notification_WakeNotification) isNotification_Notifications() {}

func (*Notification_VotingNotification) isNotification_Notifications() {}

func (*Notification_VotingResultNotification) isNotification_Notifications() {}

func (*Notification_RolePublicationNotification) isNotification_Notifications() {}

func (*Notification_ReceiveMessageNotification) isNotification_Notifications() {}

func (*Notification_FinishNotification) isNotification_Notifications() {}

var File_pkg_proto_notification_notification_proto protoreflect.FileDescriptor

var file_pkg_proto_notification_notification_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x52, 0x0a, 0x1f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2f, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x9e, 0x01, 0x0a, 0x10, 0x57, 0x61, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x41, 0x0a, 0x0d,
	0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c,
	0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x22, 0x7a, 0x0a, 0x12, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x75, 0x0a,
	0x18, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x0f, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x12, 0x0a, 0x10, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x1b, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x67, 0x0a, 0x1a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a,
	0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x5f, 0x77, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4d,
	0x61, 0x66, 0x69, 0x61, 0x57, 0x6f, 0x6e, 0x22, 0xf0, 0x06, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x7c, 0x0a, 0x22, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65,
	0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x1f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5d, 0x0a, 0x17, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x15,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x11, 0x77, 0x61, 0x6b, 0x65, 0x5f, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x57, 0x61, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x10, 0x77, 0x61, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x53, 0x0a, 0x13, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x12, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x66, 0x0a, 0x1a, 0x76, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x18, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x6f, 0x0a, 0x1d, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x1b, 0x72, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x1c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x1a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x53, 0x0a, 0x13, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x12, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x9d, 0x01, 0x0a, 0x10, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x45,
	0x57, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41,
	0x4b, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x4f, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04,
	0x12, 0x11, 0x0a, 0x0d, 0x56, 0x4f, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x50, 0x55, 0x42, 0x4c,
	0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x43,
	0x45, 0x49, 0x56, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x07, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x08, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x61,
	0x66, 0x69, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_proto_notification_notification_proto_rawDescOnce sync.Once
	file_pkg_proto_notification_notification_proto_rawDescData = file_pkg_proto_notification_notification_proto_rawDesc
)

func file_pkg_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_pkg_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_pkg_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_notification_notification_proto_rawDescData)
	})
	return file_pkg_proto_notification_notification_proto_rawDescData
}

var file_pkg_proto_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_notification_notification_proto_goTypes = []interface{}{
	(NotificationType)(0),                   // 0: notification.NotificationType
	(*ConnectionNewPlayerNotification)(nil), // 1: notification.ConnectionNewPlayerNotification
	(*StartGameNotification)(nil),           // 2: notification.StartGameNotification
	(*WakeNotification)(nil),                // 3: notification.WakeNotification
	(*VotingNotification)(nil),              // 4: notification.VotingNotification
	(*VotingResultNotification)(nil),        // 5: notification.VotingResultNotification
	(*RolePublicationNotification)(nil),     // 6: notification.RolePublicationNotification
	(*ReceiveMessageNotification)(nil),      // 7: notification.ReceiveMessageNotification
	(*FinishNotification)(nil),              // 8: notification.FinishNotification
	(*Notification)(nil),                    // 9: notification.Notification
	(*player_info.PlayerInfo)(nil),          // 10: player_info.PlayerInfo
}
var file_pkg_proto_notification_notification_proto_depIdxs = []int32{
	10, // 0: notification.ConnectionNewPlayerNotification.player:type_name -> player_info.PlayerInfo
	10, // 1: notification.StartGameNotification.player:type_name -> player_info.PlayerInfo
	10, // 2: notification.WakeNotification.remaining:type_name -> player_info.PlayerInfo
	10, // 3: notification.WakeNotification.killed_player:type_name -> player_info.PlayerInfo
	10, // 4: notification.VotingNotification.voter:type_name -> player_info.PlayerInfo
	10, // 5: notification.VotingNotification.candidate:type_name -> player_info.PlayerInfo
	10, // 6: notification.VotingResultNotification.executed_player:type_name -> player_info.PlayerInfo
	10, // 7: notification.RolePublicationNotification.player:type_name -> player_info.PlayerInfo
	10, // 8: notification.ReceiveMessageNotification.sender:type_name -> player_info.PlayerInfo
	1,  // 9: notification.Notification.connection_new_player_notification:type_name -> notification.ConnectionNewPlayerNotification
	2,  // 10: notification.Notification.start_game_notification:type_name -> notification.StartGameNotification
	3,  // 11: notification.Notification.wake_notification:type_name -> notification.WakeNotification
	4,  // 12: notification.Notification.voting_notification:type_name -> notification.VotingNotification
	5,  // 13: notification.Notification.voting_result_notification:type_name -> notification.VotingResultNotification
	6,  // 14: notification.Notification.role_publication_notification:type_name -> notification.RolePublicationNotification
	7,  // 15: notification.Notification.receive_message_notification:type_name -> notification.ReceiveMessageNotification
	8,  // 16: notification.Notification.finish_notification:type_name -> notification.FinishNotification
	0,  // 17: notification.Notification.type:type_name -> notification.NotificationType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_proto_notification_notification_proto_init() }
func file_pkg_proto_notification_notification_proto_init() {
	if File_pkg_proto_notification_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_notification_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionNewPlayerNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WakeNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VotingNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VotingResultNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePublicationNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveMessageNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_notification_notification_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_notification_notification_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_pkg_proto_notification_notification_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_pkg_proto_notification_notification_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Notification_ConnectionNewPlayerNotification)(nil),
		(*Notification_StartGameNotification)(nil),
		(*Notification_WakeNotification)(nil),
		(*Notification_VotingNotification)(nil),
		(*Notification_VotingResultNotification)(nil),
		(*Notification_RolePublicationNotification)(nil),
		(*Notification_ReceiveMessageNotification)(nil),
		(*Notification_FinishNotification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_notification_notification_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_pkg_proto_notification_notification_proto_depIdxs,
		EnumInfos:         file_pkg_proto_notification_notification_proto_enumTypes,
		MessageInfos:      file_pkg_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_pkg_proto_notification_notification_proto = out.File
	file_pkg_proto_notification_notification_proto_rawDesc = nil
	file_pkg_proto_notification_notification_proto_goTypes = nil
	file_pkg_proto_notification_notification_proto_depIdxs = nil
}
