// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: pkg/proto/player_info/player_info.proto

package player_info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_TOWNIE       Role = 0
	Role_COMMISSIONER Role = 1
	Role_MAFIA        Role = 2
	Role_KILLED       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "TOWNIE",
		1: "COMMISSIONER",
		2: "MAFIA",
		3: "KILLED",
	}
	Role_value = map[string]int32{
		"TOWNIE":       0,
		"COMMISSIONER": 1,
		"MAFIA":        2,
		"KILLED":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_player_info_player_info_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pkg_proto_player_info_player_info_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_player_info_player_info_proto_rawDescGZIP(), []int{0}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role      Role   `protobuf:"varint,1,opt,name=role,proto3,enum=player_info.Role" json:"role,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid      string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Asleep    bool   `protobuf:"varint,5,opt,name=asleep,proto3" json:"asleep,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_player_info_player_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_player_info_player_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_player_info_player_info_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_TOWNIE
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PlayerInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerInfo) GetAsleep() bool {
	if x != nil {
		return x.Asleep
	}
	return false
}

var File_pkg_proto_player_info_player_info_proto protoreflect.FileDescriptor

var file_pkg_proto_player_info_player_info_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x2a, 0x3b, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x4f, 0x57, 0x4e, 0x49, 0x45, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x46, 0x49, 0x41, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x4b, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_player_info_player_info_proto_rawDescOnce sync.Once
	file_pkg_proto_player_info_player_info_proto_rawDescData = file_pkg_proto_player_info_player_info_proto_rawDesc
)

func file_pkg_proto_player_info_player_info_proto_rawDescGZIP() []byte {
	file_pkg_proto_player_info_player_info_proto_rawDescOnce.Do(func() {
		file_pkg_proto_player_info_player_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_player_info_player_info_proto_rawDescData)
	})
	return file_pkg_proto_player_info_player_info_proto_rawDescData
}

var file_pkg_proto_player_info_player_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_player_info_player_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_player_info_player_info_proto_goTypes = []interface{}{
	(Role)(0),          // 0: player_info.Role
	(*PlayerInfo)(nil), // 1: player_info.PlayerInfo
}
var file_pkg_proto_player_info_player_info_proto_depIdxs = []int32{
	0, // 0: player_info.PlayerInfo.role:type_name -> player_info.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_player_info_player_info_proto_init() }
func file_pkg_proto_player_info_player_info_proto_init() {
	if File_pkg_proto_player_info_player_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_player_info_player_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_player_info_player_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_player_info_player_info_proto_goTypes,
		DependencyIndexes: file_pkg_proto_player_info_player_info_proto_depIdxs,
		EnumInfos:         file_pkg_proto_player_info_player_info_proto_enumTypes,
		MessageInfos:      file_pkg_proto_player_info_player_info_proto_msgTypes,
	}.Build()
	File_pkg_proto_player_info_player_info_proto = out.File
	file_pkg_proto_player_info_player_info_proto_rawDesc = nil
	file_pkg_proto_player_info_player_info_proto_goTypes = nil
	file_pkg_proto_player_info_player_info_proto_depIdxs = nil
}
